"""Audit log action constants."""
from __future__ import annotations


class AuditAction:
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_SUSPENDED = "USER_SUSPENDED"
    USER_ACTIVATED = "USER_ACTIVATED"
    ROLE_CHANGED = "ROLE_CHANGED"
    CREDIT_TRANSFERRED = "CREDIT_TRANSFERRED"
    GAME_CREATED = "GAME_CREATED"
    GAME_UPDATED = "GAME_UPDATED"
    SETTINGS_CHANGED = "SETTINGS_CHANGED"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    IMPERSONATION_STARTED = "IMPERSONATION_STARTED"
    IMPERSONATION_ENDED = "IMPERSONATION_ENDED"
    BET_PLACED = "BET_PLACED"
